import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPromotionItemsJoinTable1779141392876 implements MigrationInterface {
    name = 'AddPromotionItemsJoinTable1779141392876'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "fk_time_entries_user"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "fk_time_entries_edited_by"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "fk_user_preferences_user"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP CONSTRAINT "fk_catalog_category"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "fk_sale_lines_sale"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "fk_sale_lines_item"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "fk_sale_lines_discount_by"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "fk_sale_payments_sale"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "fk_sales_employee"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "fk_sales_voided_by"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP CONSTRAINT "fk_inventory_product"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP CONSTRAINT "fk_inventory_created_by"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "fk_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "fk_audit_log_user"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "fk_alerts_resolved_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_pin_unique"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_pin"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_sku"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sale_lines_item"`);
        await queryRunner.query(`CREATE TABLE "promotion_items" ("promotion_id" uuid NOT NULL, "item_id" uuid NOT NULL, CONSTRAINT "PK_78f8725c6b3a2ba99895897643f" PRIMARY KEY ("promotion_id", "item_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac1036add91b29c71b4c2aefe5" ON "promotion_items" ("promotion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5177a9642ff1353fbe5e610053" ON "promotion_items" ("item_id") `);
        await queryRunner.query(`ALTER TYPE "public"."role_enum" RENAME TO "role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'empleada')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'empleada'`);
        await queryRunner.query(`DROP TYPE "public"."role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'empleada'`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_enum" RENAME TO "user_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('activa', 'vacaciones', 'inactiva')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum" USING "status"::"text"::"public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'activa'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."pay_type_enum" RENAME TO "pay_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_pay_type_enum" AS ENUM('salario', 'salario + comisión', 'comisión')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pay_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pay_type" TYPE "public"."users_pay_type_enum" USING "pay_type"::"text"::"public"."users_pay_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pay_type" SET DEFAULT 'salario'`);
        await queryRunner.query(`DROP TYPE "public"."pay_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."time_entry_source_enum" RENAME TO "time_entry_source_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."time_entries_source_enum" AS ENUM('ui', 'manual')`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "source" TYPE "public"."time_entries_source_enum" USING "source"::"text"::"public"."time_entries_source_enum"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "source" SET DEFAULT 'ui'`);
        await queryRunner.query(`DROP TYPE "public"."time_entry_source_enum_old"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."item_type_enum"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD "type" character(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD "image" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."discount_kind_enum" RENAME TO "discount_kind_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sale_lines_discount_kind_enum" AS ENUM('amount', 'percent')`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_suggested_offer_kind_enum" AS ENUM('amount', 'percent')`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ALTER COLUMN "discount_kind" TYPE "public"."sale_lines_discount_kind_enum" USING "discount_kind"::"text"::"public"."sale_lines_discount_kind_enum"`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "suggested_offer_kind" TYPE "public"."alerts_suggested_offer_kind_enum" USING "suggested_offer_kind"::"text"::"public"."alerts_suggested_offer_kind_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discount_kind_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum" RENAME TO "payment_method_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sale_payments_method_enum" AS ENUM('cash', 'card', 'transfer')`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ALTER COLUMN "method" TYPE "public"."sale_payments_method_enum" USING "method"::"text"::"public"."sale_payments_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_employee_date_status"`);
        await queryRunner.query(`ALTER TYPE "public"."sale_status_enum" RENAME TO "sale_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('completed', 'voided')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sales_status_enum" USING "status"::"text"::"public"."sales_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" SET DEFAULT 'completed'`);
        await queryRunner.query(`DROP TYPE "public"."sale_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."inventory_kind_enum" RENAME TO "inventory_kind_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_entries_kind_enum" AS ENUM('purchase', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ALTER COLUMN "kind" TYPE "public"."inventory_entries_kind_enum" USING "kind"::"text"::"public"."inventory_entries_kind_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_kind_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."adjustment_reason_enum" RENAME TO "adjustment_reason_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_entries_reason_enum" AS ENUM('conteo', 'merma', 'robo', 'uso', 'devolucion')`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ALTER COLUMN "reason" TYPE "public"."inventory_entries_reason_enum" USING "reason"::"text"::"public"."inventory_entries_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adjustment_reason_enum_old"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."bonus_metric_enum" RENAME TO "bonus_metric_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."goals_metric_enum" AS ENUM('totalSales', 'retailSales', 'servicesDone', 'newClients', 'tipsCollected')`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "metric" TYPE "public"."goals_metric_enum" USING "metric"::"text"::"public"."goals_metric_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bonus_metric_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."reward_type_enum" RENAME TO "reward_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."goals_reward_type_enum" AS ENUM('fixed', 'percent')`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "reward_type" TYPE "public"."goals_reward_type_enum" USING "reward_type"::"text"::"public"."goals_reward_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reward_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."goal_tone_enum" RENAME TO "goal_tone_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."goals_tone_enum" AS ENUM('magenta', 'purple', 'teal', 'green')`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "tone" TYPE "public"."goals_tone_enum" USING "tone"::"text"::"public"."goals_tone_enum"`);
        await queryRunner.query(`DROP TYPE "public"."goal_tone_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alerts_type_status"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_type_enum" RENAME TO "alert_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_type_enum" AS ENUM('low_stock', 'discount_review', 'slow_mover', 'promo')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "type" TYPE "public"."alerts_type_enum" USING "type"::"text"::"public"."alerts_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alert_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_status_enum" RENAME TO "alert_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_status_enum" AS ENUM('active', 'resolved', 'snoozed')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "status" TYPE "public"."alerts_status_enum" USING "status"::"text"::"public"."alerts_status_enum"`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."alert_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "notes" character varying`);
        await queryRunner.query(`CREATE INDEX "uniq_sku" ON "catalog_items" ("sku") WHERE sku IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_sales_employee_date_status" ON "sales" ("employee_id", "created_at", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_alerts_type_status" ON "alerts" ("type", "status") `);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_e86a2cf7abe23916b0938c89a05" FOREIGN KEY ("edited_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD CONSTRAINT "FK_c3b570d8f28acd0bb1e873d2f3c" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "FK_3c1694f38a418f7ad3335ecce96" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "FK_4c90c7c8fff7468c8280814a7e3" FOREIGN KEY ("item_id") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "FK_f966e52fd0397e72793ee8b9c8e" FOREIGN KEY ("discount_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_731ffab2e5e639ef1326117c17b" FOREIGN KEY ("employee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_1f6ba72ea05d74c58edcd771ae3" FOREIGN KEY ("voided_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD CONSTRAINT "FK_b42c34339d9202e09579824ad92" FOREIGN KEY ("product_id") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD CONSTRAINT "FK_6305345a10bf65348675bced43d" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_f24ed04d19fdae8c55b4f6f2324" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotion_items" ADD CONSTRAINT "FK_ac1036add91b29c71b4c2aefe5e" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "promotion_items" ADD CONSTRAINT "FK_5177a9642ff1353fbe5e6100535" FOREIGN KEY ("item_id") REFERENCES "catalog_items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "promotion_items" DROP CONSTRAINT "FK_5177a9642ff1353fbe5e6100535"`);
        await queryRunner.query(`ALTER TABLE "promotion_items" DROP CONSTRAINT "FK_ac1036add91b29c71b4c2aefe5e"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_f24ed04d19fdae8c55b4f6f2324"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP CONSTRAINT "FK_6305345a10bf65348675bced43d"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP CONSTRAINT "FK_b42c34339d9202e09579824ad92"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_1f6ba72ea05d74c58edcd771ae3"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_731ffab2e5e639ef1326117c17b"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "FK_f966e52fd0397e72793ee8b9c8e"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "FK_4c90c7c8fff7468c8280814a7e3"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "FK_3c1694f38a418f7ad3335ecce96"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP CONSTRAINT "FK_c3b570d8f28acd0bb1e873d2f3c"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_e86a2cf7abe23916b0938c89a05"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alerts_type_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_employee_date_status"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_sku"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "notes" text`);
        await queryRunner.query(`CREATE TYPE "public"."discount_kind_enum_old" AS ENUM('amount', 'percent')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "suggested_offer_kind" TYPE "public"."discount_kind_enum_old" USING "suggested_offer_kind"::"text"::"public"."discount_kind_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_suggested_offer_kind_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."discount_kind_enum_old" RENAME TO "discount_kind_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."alert_status_enum_old" AS ENUM('active', 'resolved', 'snoozed')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "status" TYPE "public"."alert_status_enum_old" USING "status"::"text"::"public"."alert_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."alerts_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_status_enum_old" RENAME TO "alert_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."alert_type_enum_old" AS ENUM('low_stock', 'discount_review', 'slow_mover', 'promo')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "type" TYPE "public"."alert_type_enum_old" USING "type"::"text"::"public"."alert_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_type_enum_old" RENAME TO "alert_type_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_alerts_type_status" ON "alerts" ("status", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."goal_tone_enum_old" AS ENUM('magenta', 'purple', 'teal', 'green')`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "tone" TYPE "public"."goal_tone_enum_old" USING "tone"::"text"::"public"."goal_tone_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."goals_tone_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."goal_tone_enum_old" RENAME TO "goal_tone_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."reward_type_enum_old" AS ENUM('fixed', 'percent')`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "reward_type" TYPE "public"."reward_type_enum_old" USING "reward_type"::"text"::"public"."reward_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."goals_reward_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reward_type_enum_old" RENAME TO "reward_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."bonus_metric_enum_old" AS ENUM('totalSales', 'retailSales', 'servicesDone', 'newClients', 'tipsCollected')`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "metric" TYPE "public"."bonus_metric_enum_old" USING "metric"::"text"::"public"."bonus_metric_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."goals_metric_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."bonus_metric_enum_old" RENAME TO "bonus_metric_enum"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD "notes" text`);
        await queryRunner.query(`CREATE TYPE "public"."adjustment_reason_enum_old" AS ENUM('conteo', 'merma', 'robo', 'uso', 'devolucion')`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ALTER COLUMN "reason" TYPE "public"."adjustment_reason_enum_old" USING "reason"::"text"::"public"."adjustment_reason_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_entries_reason_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."adjustment_reason_enum_old" RENAME TO "adjustment_reason_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_kind_enum_old" AS ENUM('purchase', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ALTER COLUMN "kind" TYPE "public"."inventory_kind_enum_old" USING "kind"::"text"::"public"."inventory_kind_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_entries_kind_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."inventory_kind_enum_old" RENAME TO "inventory_kind_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."sale_status_enum_old" AS ENUM('completed', 'voided')`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" TYPE "public"."sale_status_enum_old" USING "status"::"text"::"public"."sale_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "status" SET DEFAULT 'completed'`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sale_status_enum_old" RENAME TO "sale_status_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_sales_employee_date_status" ON "sales" ("created_at", "employee_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum_old" AS ENUM('cash', 'card', 'transfer')`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ALTER COLUMN "method" TYPE "public"."payment_method_enum_old" USING "method"::"text"::"public"."payment_method_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sale_payments_method_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum_old" RENAME TO "payment_method_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."discount_kind_enum_old" AS ENUM('amount', 'percent')`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ALTER COLUMN "discount_kind" TYPE "public"."discount_kind_enum_old" USING "discount_kind"::"text"::"public"."discount_kind_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sale_lines_discount_kind_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."discount_kind_enum_old" RENAME TO "discount_kind_enum"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD "image" text`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."item_type_enum" AS ENUM('S', 'P')`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD "type" "public"."item_type_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."time_entry_source_enum_old" AS ENUM('ui', 'manual')`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "source" TYPE "public"."time_entry_source_enum_old" USING "source"::"text"::"public"."time_entry_source_enum_old"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "source" SET DEFAULT 'ui'`);
        await queryRunner.query(`DROP TYPE "public"."time_entries_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."time_entry_source_enum_old" RENAME TO "time_entry_source_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."pay_type_enum_old" AS ENUM('salario', 'salario + comisión', 'comisión')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pay_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pay_type" TYPE "public"."pay_type_enum_old" USING "pay_type"::"text"::"public"."pay_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pay_type" SET DEFAULT 'salario'`);
        await queryRunner.query(`DROP TYPE "public"."users_pay_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pay_type_enum_old" RENAME TO "pay_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum_old" AS ENUM('activa', 'vacaciones', 'inactiva')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."user_status_enum_old" USING "status"::"text"::"public"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'activa'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_enum_old" RENAME TO "user_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."role_enum_old" AS ENUM('admin', 'empleada')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."role_enum_old" USING "role"::"text"::"public"."role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."role_enum_old" RENAME TO "role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5177a9642ff1353fbe5e610053"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac1036add91b29c71b4c2aefe5"`);
        await queryRunner.query(`DROP TABLE "promotion_items"`);
        await queryRunner.query(`CREATE INDEX "idx_sale_lines_item" ON "sale_lines" ("item_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_sku" ON "catalog_items" ("sku") WHERE (sku IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_pin" ON "users" ("pin_hash") WHERE (status <> 'inactiva'::user_status_enum)`);
        await queryRunner.query(`CREATE INDEX "idx_users_pin_unique" ON "users" ("pin_hash") `);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "fk_alerts_resolved_by" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "fk_audit_log_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD CONSTRAINT "fk_inventory_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD CONSTRAINT "fk_inventory_product" FOREIGN KEY ("product_id") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_sales_voided_by" FOREIGN KEY ("voided_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_sales_employee" FOREIGN KEY ("employee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "fk_sale_payments_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "fk_sale_lines_discount_by" FOREIGN KEY ("discount_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "fk_sale_lines_item" FOREIGN KEY ("item_id") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "fk_sale_lines_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD CONSTRAINT "fk_catalog_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "fk_user_preferences_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "fk_time_entries_edited_by" FOREIGN KEY ("edited_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "fk_time_entries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
