[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm build && pnpm migration:run"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
